CI: download _site

diff --git a/.github/workflows/deploy-al-folio.yml b/.github/workflows/deploy-al-folio.yml
--- a/.github/workflows/deploy-al-folio.yml
+++ b/.github/workflows/deploy-al-folio.yml
@@ -64,12 +64,11 @@ on:
 
 permissions:
   contents: write
-  pages: write    # Required for GitHub Pages deployment
-  id-token: write # Required for OIDC token in actions/deploy-pages@v4
+  pages: write
+  id-token: write
 
 jobs:
   build:
-    # available images: https://github.com/actions/runner-images#available-images
     runs-on: ubuntu-latest
     steps:
       - name: Checkout 🛎️
@@ -83,7 +82,7 @@ jobs:
         uses: actions/setup-python@v5
         with:
           python-version: "3.13"
-          cache: "pip" # caching pip dependencies
+          cache: "pip"
       - name: Update _config.yml ⚙️
         uses: fjogeleit/yaml-update-action@main
         with:
@@ -96,18 +95,35 @@ jobs:
           sudo apt-get update && sudo apt-get install -y imagemagick
           pip3 install --upgrade nbconvert
           export JEKYLL_ENV=production
-          bundle exec jekyll build
+          bundle exec jekyll build || { echo "Jekyll build failed"; exit 1; }
       - name: Purge unused CSS 🧹
         run: |
           npm install -g purgecss
-          purgecss -c purgecss.config.js
-  
+          purgecss -c purgecss.config.js || { echo "PurgeCSS failed"; exit 1; }
+      - name: List _site contents 🕵️
+        if: github.event_name != 'pull_request'
+        run: ls -la _site
+      - name: Upload artifact 📦
+        if: github.event_name != 'pull_request'
+        uses: actions/upload-artifact@v4
+        with:
+          name: site-artifact
+          path: _site
+          retention-days: 1
+
   deploy:
     runs-on: ubuntu-latest
     needs: build
+    if: github.event_name != 'pull_request'
     steps:
+      - name: Download artifact 📥
+        uses: actions/download-artifact@v4
+        with:
+          name: site-artifact
+          path: _site
+      - name: List downloaded _site contents 🕵️
+        run: ls -la _site
       - name: Deploy 🚀
-        if: github.event_name != 'pull_request'
         uses: JamesIves/github-pages-deploy-action@v4
         with:
           folder: _site
